### ISSUE TITLE
energized is dead

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [yokoffing/NextDNS-Config#10]
https://github.com/nextdns/metadata/issues/1145
please remove Energized Ultimate from your Aggressive Blocklists

**Comment by yokoffing** [comment]
https://www.reddit.com/r/nextdns/comments/z49c93/state_of_affairs_at_the_moment_lol/
https://www.reddit.com/r/nextdns/comments/z444bn/intermittent_issues/
https://www.reddit.com/r/nextdns/comments/z4a7ov/energized_lists_all_hacked_or_another_issue/
https://help.nextdns.io/t/m1hs207/energized-ultimate-lists-blocking-nextdns
https://github.com/nextdns/metadata/issues/1145#issuecomment-1327948021

> their latest commit emptied the [README.md](http://readme.md/) file from their official repo. See https://github.com/EnergizedProtection/block/commit/8bc981b5b1e813ab07ea80cbb08e4b42643d9b6e

oh my
