### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by marcoclg19** [yokoffing/NextDNS-Config#18]
First of all, Happy New Year and thank you for this helpful guide!

1. How do you manage the use of multiple browsers on the iPhone? If I use Orion for my daily browsing, then Safari would no longer be used? 
2. As adblock for Safari is AdGuard better than 1Blocker or Ghostery for iOS? How do you configure AdGuard if one already has protection with some lists through NextDNS?  (Will the free version be enough?)

Cheers!

**Comment by yokoffing** [comment]
> How do you manage the use of multiple browsers on the iPhone?

I use a variety of browsers for iPhone: Orion or Brave are good for YouTube; Safari with AdGuard is good for most general needs; DuckDuckGo browser if I need something with less blocking.

> adblock for Safari is AdGuard better than 1Blocker or Ghostery for iOS?

Yes, IMO. I rotate them out occasionally to see if anything’s changed.

> How do you configure AdGuard if one already has protection with some lists through NextDNS? (Will the free version be enough?)

Free version should be okay. Defaults are fine, but you can add AdGuard and FanBoy Annoyances list too.

**Comment by marcoclg19** [comment]
> I use a variety of browsers for iPhone

Which one do you usually keep as your default?

> Yes, IMO. I rotate them out occasionally to see if anything’s changed.

I have yet to understand why Ghostery does not use the Safari content blocker...

**Comment by yokoffing** [comment]
Safari
