### ISSUE TITLE
redefine Aggressive blocklists

### ISSUE THREAD

**Issue by yokoffing** [yokoffing/NextDNS-Config#27]
> maybe 1Hosts (Xtra) should be removed?
> there are too much false positives: `github.com/badmojr/1Hosts/issues?q=xtra`

_Originally posted by @bestplayerbot in https://github.com/yokoffing/NextDNS-Config/issues/26#issuecomment-1455506819_

**Comment by yokoffing** [comment]
@bestplayerbot I'm not opposed to removing 1Host (Xtra). I just haven't decided on how to reword the description for Aggressive.

Currently, we have:

Aggressive: excessive breakage; many false positives; use on a separate profile to [lockdown single-purpose devices](https://old.reddit.com/r/nextdns/comments/uqap3n/comment/i8q8alf/?context=3)
The current definition doesn't really apply to Hagezi Ultimate, only to 1Host Xtra.

We could use similar language as Hagezi and say,

Aggressive: frequent breakage; should only be used by experienced users
Thoughts? @hagezi @iam-py-test

**Comment by hagezi** [comment]
"Aggressive: frequent breakage; should only be used by experienced users" fits best in my opinion.

As for 1Host extra, it contains a lot of false positive domains, but it seems that there are users who use such lists - even if the sense behind it is not clear to me. Therefore I would not remove it.
