### ISSUE TITLE
NX Enhanced extension

### ISSUE THREAD

**Issue by nyas1** [yokoffing/NextDNS-Config#29]
Came across this really useful extension [NX Enhanced](https://github.com/hjk789/NXEnhanced), thought you should add it in your config since adds really nice features like:
- Allow/Deny buttons in the logs
- Refine a search with multiple search terms or exclusion terms
- Ability to export/import all settings from/to a config
- Option to show only queries from unnamed devices
- Collapse the list of blocklists enabled
- Sort alphabetically the list of blocklists & more..

**Comment by yokoffing** [comment]
Thank you for your suggestion. NX Enhanced adds some cool features to NextDNS. Where do you think it should be mentioned on the Github page?

**Comment by nyas1** [comment]
maybe a new section like "Add-ons 🧩" or "Extensions"?

**Comment by yokoffing** [comment]
The repo mirrors the NextDNS settings pages, so I would probably put it in the FAQ section.

**Comment by nyas1** [comment]
okay👍
