### ISSUE TITLE
Question regarding cryptojacking toggle

### ISSUE THREAD

**Issue by devipasigner** [yokoffing/NextDNS-Config#31]
All recommended lists (and alternate) include the cryptojacking list in NextDNS's built in cryptojacking protection. (with additional false positives removed).

So my question is why advise people to enable it? One of the lists are not maintained often and hagezi has stripped some false positives out of it.

**Comment by yokoffing** [comment]
Just thinking out loud: NextDNS [internalized](https://github.com/nextdns/metadata#readme) many of their lists, which weakened the case for this. They probably still use those one or two lists, but we cannot confirm that.

If we assume they use the same two lists:
- We could view this as a defense-in-depth and keep it enabled.
- We could encounter false positives that NextDNS does not allowlist but other maintainers do, and recommend users disable Cryptojacking Protection (your point).

Questions: Should we leave it enabled in case someone doesn't use the recommended privacy blocklists? What about the user who utilizes different lists?

cc: @hagezi

**Comment by hagezi** [comment]
I have activated it and have had no problems so far. Unfortunately, you can not see what is behind this function, because the lists are internal and not public. Maybe @romaincointepas or @rs can give information about this?

**Comment by SpidaXS** [comment]
> I have activated it and have had no problems so far. Unfortunately, you can not see what is behind this function, because the lists are internal and not public. Maybe @romaincointepas or @rs can give information about this?

I don't recommend you enable this, there are many more false positive

**Comment by iam-py-test** [comment]
This is a known issue with the NoCoin filterlist (which I guess they are using?): https://github.com/hoshsadiq/adblock-nocoin-list/issues/452
