### ISSUE TITLE
Re Native Tracking Protection

### ISSUE THREAD

**Issue by srgdvd** [yokoffing/NextDNS-Config#40]
Disabling Native Tracking Protection for brands which manufacture IoT and connected/"smart" devices and appliances, could prevent confining them, and sometimes even discovering them via their mobile apps. 

For example, when trying to update the changed home WiFi settings for Amazon Echo device, I could not access its configuration page in Alexa mobile app on iPhone even after connecting the iPhone to the speaker's own default WiFi which it emits in a set-up mode.

I **disabled** Native Tracking Protection for Amazon in my NextDNS profile for iPhone, and was able to have this speaker be "discovered" in the app and access its config page.
It could scan and discover my new home WiFi, I entered the password for it, but the speaker was not able to finish the set up for for a new WiFi. Only when I disabled Native Tracking Protection for Amazon in the NextDNS profile for my router, the procedure could be completed. 

Then I re-enabled blocking (Native Tracking Protection) for Amazon and the Echo speaker kept working fine, including all interaction between it and Alexa mobile app.

So this is a warning, that at least during discovery/configuration of IoT and connected/"smart" devices, you might need to disable Native Tracking Protection for their manufacturer brand.

**Comment by yokoffing** [comment]
As much as I protest having Alexa in my house, one of my family member's uses it. We've had this issue happen before, but I'm unsure if I can blame it on Native Tracking Protection.
