### ISSUE TITLE
Wifi restricting the use of nextDNS, no longer working

### ISSUE THREAD

**Issue by GrayLanterns** [yokoffing/NextDNS-Config#42]
Hey, my wifi seems to be restricting the use of nextDNS. No website is loading as long as I'm connected to nextDNS. It worked normally for a few days, up till this point. Can you please help?

**Comment by yokoffing** [comment]
The **Issues** tab relates to parts of the guide that need changing.

Please post your issue with more details on [r/NextDNS](https://www.reddit.com/r/nextdns/) or the [NextDNS Help Forums](https://help.nextdns.io/tag/setup), I don't have the resources to offer customer support.
