### ISSUE TITLE
the config/settings page don't work well on chrome in windows using high contrast

### ISSUE THREAD

**Issue by leao-nardo** [yokoffing/NextDNS-Config#44]
windows high contrast theme dark black . makes the toggle buttons show as all black with just a border line .
there's no way to tell if the buttons are on or off .
in the allowlist page the button are like but i can tell if on/off , because when its off the text/url become shadowed/grayed . 
if u make the settings page like this too it can be usable .

**Comment by yokoffing** [comment]
Please report to https://help.nextdns.io/
