### ISSUE TITLE
replace oisd to notracking

### ISSUE THREAD

**Issue by FadeMind** [yokoffing/NextDNS-Config#5]
Hi @yokoffing 

Please consider replace oisd to notracking blocklist. 
notracking does not have any major false positives. 
oisd after several months using it is for me too liberal with whitelisting
Also developer does not ping Original Maintainers about whitelists issue.  
NoTracking have solid base with small amount false positives (if any). 
Alongside with 1Hosts (Mini) and small custom whitelists NextDNS works like a charm. 
Please note: oisd does not have included Steven Black hosts originals and denied adding them. 

I used following whitelists (against some apps issues)
```
adocean.pl
c.msn.com
cdn-settings.appsflyersdk.com
click.redditmail.com
crashlyticsreports-pa.googleapis.com
google-analytics.com
googleads.g.doubleclick.net
googletagmanager.com
gvt1.com
gvt2.com
gvt3.com
insideruser.microsoft.com
launches.appsflyer.com
media-lab.ai
mybbc-analytics.files.bbci.co.uk
oaprodlogging.yo-digital.com
sdk-02.moengage.com
self.events.data.microsoft.com
stats.g.doubleclick.net
```

https://github.com/notracking/hosts-blocklists

**Comment by yokoffing** [comment]
Here's my observations so far:
* Despite its heavy allowlisting, `OISD` blocks domains not included in `notracking` or `1Hosts` lists
* `notracking` blocks a few domains that are not in `1Hosts (Lite)` or `OISD` (esp. Google crap),
   * but not as much as `1Hosts (Pro)` or `Lightswitch05` 
* `notracking` blocks a few of the same domains that are in `1Hosts (Pro)`, but not ones that cause significant breakage;
   * and yet, at the same time, `notracking` also _omits_ domains that are in all `1Hosts` lists and the `OISD` list

So, it seems to be a good candidate as a tertiary list for the [Balanced](https://github.com/yokoffing/NextDNS-Config#blocklists-1) tier. I've placed it as a third list before, but I've been mulling over whether it's really needed.

> oisd after several months using it is for me too liberal with whitelisting

OISD allows too much, but you use 1Hosts(Mini)????

**Comment by FadeMind** [comment]
@yokoffing I will try your recommendation (OISD + notracking + 1Hosts (Lite). Regards
