### ISSUE TITLE
Apple domains are redundant

### ISSUE THREAD

**Issue by mvevitsis** [yokoffing/NextDNS-Config#50]
All of the apple domains recommended in the denylist section are included in either NextDNS' built in apple tracking protection, or Hagezi.
You can verify it for yourself by trying to access the domains and viewing the NextDNS log.

The only one which doesn't seem to by blocked is feedbackws.fe.apple-dns.net

I also checked the recommended Twitter and Nvidia domains, those are indeed not blocked by Hagezi.

**Comment by yokoffing** [comment]
Yeah. The denylist and allowlist sections were made prior to Hagezi being a thing. I've kept them there for reference.

**Comment by aZRGaOmjIw** [comment]
HaGeZi - Multi ULTIMATE is blocking this domain
