### ISSUE TITLE
Amazon Australia blocked

### ISSUE THREAD

**Issue by terrainer** [yokoffing/NextDNS-Config#51]
Amazon Australia gets blocked by various blocklists, including Hagezi. See https://github.com/hagezi/dns-blocklists/issues/2073

**Comment by hagezi** [comment]
It has now been fixed everywhere except in NextDNS and DNS0.eu, both services from the same makers and without support. I reported this to DNS0.eu a few days ago, but nothing happened.

The source was the malware filter phishing list, in which CNAMES for Amazon NL and AU were listed.

**Comment by yokoffing** [comment]
I am closing this issue report because the maintainers have updated the source lists.

**Comment by terrainer** [comment]
> It has now been fixed everywhere except in NextDNS and DNS0.eu, both services from the same makers and without support. I reported this to DNS0.eu a few days ago, but nothing happened.
> 
> The source was the malware filter phishing list, in which CNAMES for Amazon NL and AU were listed.
> 
> However, this has now also been fixed in the source lists.

Might be something on my end, but I still need to allow those 3 domains to use the app
