### ISSUE TITLE
The block page causes so many problems ...

### ISSUE THREAD

**Issue by hagezi** [yokoffing/NextDNS-Config#54]
Yet another example that the block page should be banned from NextDNS:
https://help.nextdns.io/t/g9yxqcd/nextdns-blocking-hoyolab

@rs @romaincointepas please disable it.

**Comment by yokoffing** [comment]
@hagezi Just checking: The link does not specify the block page setting as the issue. You came across this issue and tested it?

**Comment by hagezi** [comment]
Link from Thread:

https://help.nextdns.io/t/83yxjgx/most-common-problem-with-nextdns

**Comment by yokoffing** [comment]
added
