### ISSUE TITLE
" if you configure Safari to hide your IP from trackers only, it will bypass NextDNS for those domains"

### ISSUE THREAD

**Issue by wolffcatskyy** [yokoffing/NextDNS-Config#57]
If this is true, maybe it should be included?  Are there other issues with Private Relay that are relevant?

https://www.reddit.com/r/nextdns/comments/zy16jp/comment/j23lryk/

**Comment by yokoffing** [comment]
It's a year old post, and I'm not aware of any recent issues. I'd rather wait until there's there's confirmation of a problem, and for the problem to be more common than uncommon.

A year has passed since the original post, and I'm not aware of any recent issues. Before proceeding, I prefer to wait for confirmation that a problem exists and that it affects a significant number of users.

**Comment by BirdInFire** [comment]
> It's a year old post, and I'm not aware of any recent issues. I'd rather wait until there's there's confirmation of a problem, and for the problem to be more common than uncommon.
> 
> A year has passed since the original post, and I'm not aware of any recent issues. Before proceeding, I prefer to wait for confirmation that a problem exists and that it affects a significant number of users.

It may not be related, but some time ago I had bypass of blocked domain when using the relay, using "NXdomain" as answer for blocked query fixed it when the relay was on.

worth trying I guess

**Comment by yokoffing** [comment]
Added https://github.com/yokoffing/NextDNS-Config/tree/main?tab=readme-ov-file#block-access-to-icloud-private-relay

**Comment by peterpme** [comment]
I've noticed some issues recently when private relay is enabled. 

Dumb question: does this mean that we should disable private relay completely on the devices that use this setup?

**Comment by BudgieBird** [comment]
I've noticed these issues as well but only recently.

**Comment by yokoffing** [comment]
@peterpme @BudgieBird Did you try https://github.com/yokoffing/NextDNS-Config/tree/main?tab=readme-ov-file#icloud-private-relay?

**Comment by BudgieBird** [comment]
Just threw them on the deny list. I'll see how that works out, thanks.
