### ISSUE TITLE
[help] if I use HaGeZi ultimate does it cover all?

### ISSUE THREAD

**Issue by redcat42** [yokoffing/NextDNS-Config#58]
hi,

thank you for this easy-to-follow guide 

I'm not nitpicking, just tying to understand, if I use 'HaGeZi ultimate' list, then, do I still need to use 'HaGeZi Normal' and 'HaGeZi pro+' as suggested in the guide...

in short, does HaGeZi Ultimate cover all of HaGeZi's lists combined

thanks

**Comment by trivarialthea** [comment]
Yes. 

You can read more about it in the hazegi github repo. 
https://github.com/hagezi/dns-blocklists/tree/main?tab=readme-ov-file#blocklist-version-and-size-overview

**Comment by redcat42** [comment]
thanks. appreciate it. 

since I'm using nextdns and the size of the list does not matter, for my usage, using only ultimate works best
