### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by BirdInFire** [yokoffing/NextDNS-Config#59]
Due to the very hight amount of blocklist dead in NEXTDNS (I do not know why they don't rotate those list)

a warning can be useful for those who follow (check the last time update and number of rule) some are not updated (because dead) and some are empty 0 rules.

**Comment by bakerboy448** [comment]
Does https://github.com/yokoffing/NextDNS-Config#which-blocklist-should-i-use not cover it implicitly?

**Comment by BirdInFire** [comment]
> Does https://github.com/yokoffing/NextDNS-Config#which-blocklist-should-i-use not cover it implicitly?

Not really because here it do have nothing to do with false positive etc but more from a outdated blocklist meaning even if the list had the best rating since it's dead it will leak.

But yeah adding an additional warning here like "be careful of the last time a list was updated", because many nextdns user will may not see it and after ask why ads pass trough

**Comment by yokoffing** [comment]
> many nextdns user will may not see it and after ask why ads pass trough

So maybe NextDNS themselves should add the warning? 😆

Hagezi's blocklists are comprehensive and well-maintained. If a user chooses to deviate from the recommended setup by adding additional blocklists, that's their decision.

The guide aims to provide a streamlined, effective configuration, and any deviations from it are at the user's discretion. I already discourage using more blocklists than necessary.

**Comment by BirdInFire** [comment]
> > many nextdns user will may not see it and after ask why ads pass trough
> 
> So maybe NextDNS themselves should add the warning? 😆
> 
> Hagezi's blocklists are comprehensive and well-maintained. If a user chooses to deviate from the recommended setup by adding additional blocklists, that's their decision.
> 
> The guide aims to provide a streamlined, effective configuration, and any deviations from it are at the user's discretion. I already discourage using more blocklists than necessary.

I do agree with you, sadly NextDNS never answer to the dozen of email and call I've done to ask them (also ask why their child (dns0) do not have ipv6 ip on their DOH again complete silence.

but it's your guide your rules just asked in the tough of people who may not be tech savvy.

I will close it as not planed so :)
