### ISSUE TITLE
add Cloudflare DNS

### ISSUE THREAD

**Issue by cyriotic3** [yokoffing/NextDNS-Config#60]
is there a way to add Cloudflare DNS or is it already in it? i did a [https://one.one.one.one/help/](url) test [https://one.one.one.one/help/#eyJpc0NmIjoiTm8iLCJpc0RvdCI6Ik5vIiwiaXNEb2giOiJObyIsInJlc29sdmVySXAtMS4xLjEuMSI6IlllcyIsInJlc29sdmVySXAtMS4wLjAuMSI6IlllcyIsInJlc29sdmVySXAtMjYwNjo0NzAwOjQ3MDA6OjExMTEiOiJZZXMiLCJyZXNvbHZlcklwLTI2MDY6NDcwMDo0NzAwOjoxMDAxIjoiWWVzIiwiZGF0YWNlbnRlckxvY2F0aW9uIjoiS1VMIiwiaXNXYXJwIjoiTm8iLCJpc3BOYW1lIjoiR2lnYWJpdCBIb3N0aW5nIFNkbiBCaGQiLCJpc3BBc24iOiI1NTcyMCJ9](url) but the results shows _no_

**Comment by yokoffing** [comment]
No, Cloudflare is a separate DNS service from NextDNS...
