### ISSUE TITLE
Xbox achievements 

### ISSUE THREAD

**Issue by Levander0** [yokoffing/NextDNS-Config#62]
Hi, these domains are blocked by hagezi Ultimate but are needed for Xbox Achievements. I think these would be a great addition to the "allowlist" section.

v10.events.data.microsoft.com
v20.events.data.microsoft.com

**Comment by yokoffing** [comment]
The allowlist is mostly leftover from using lists before Hagezi was around. I also don't encourage the use of Ultimate. However, I don't mind adding these for now.
