### ISSUE TITLE
Another iCloud Private Relay server

### ISSUE THREAD

**Issue by 956ross** [yokoffing/NextDNS-Config#70]
mask-api.icloud.com
mask.apple-dns.net

also apple-relay.cloudflare.com is missing an "l" in "flare"
<img width="294" alt="Screenshot 2024-11-01 at 5 57 32 PM" src="https://github.com/user-attachments/assets/1983da37-ae3a-4477-a85a-41c0765294ab">

**Comment by yokoffing** [comment]
thanks!
