### ISSUE TITLE
Nice guide, but maybe do an option for set and forget who dont want to keep adding to whitelist.

### ISSUE THREAD

**Issue by chrcoluk** [yokoffing/NextDNS-Config#72]
It is a shame Nextdns doesnt allow adding custom feed's or doesnt support Hagezi TIF feeds manually.

For a set and forget I would perhaps do something like this.

Security - Enable child porn filter, typo protection, IDN, google safe browsing and DGN.  Disable NextDNS TIF as low quality. AI I would say off, but since no custom TIF can be added, keep this on.  Much better quality than the default NextDNS TIF.
Privacy - Disable default NextDNS filter (false positives galore). dont use native tracking protection unless you like broken devices, enable block disguised trackers if not using firefox for browsing, disable it if you are using firefox for browsing combined with ublock origin, enable hagazi light tracker list.
Settings - block page probably disable, but enabling it could potentially help device behaviour, disable web3 as thats a security issue waiting to happen, enable EDNS enhancement, disable cname flattening, user preference on cache boost my suggestion if you boosting caching locally, keep it off, otherwise enable it.

I have been doing lots of testing on the black lists offered by NextDNS, the only lists it offers that have any credibility in my opinion are hagezi and adguard DNS. which is similar to your own conclusion, adguard has an exception list to fix breakages which sadly NextDNS do not implement.  My combination if was possible would deffo be hagezi light mixed with hagezi tif medium, these are his more careful lists, but the combination blocks almost all things people will come across that his heavier lists would block, his heavier lists have false positives, and breakage, including the highly regarded pro list.  hagezi normal also did well in my test, but light was close enough to it, making that one win out.

Its a shame NextDNS do not allow adding whitelist feeds, and dont allow adding Hagezi TIF feeds.

**Comment by yokoffing** [comment]
No clear ask.

Copy of a Reddit post;
https://www.reddit.com/r/nextdns/comments/1hd4022/set_and_forget_for_nextdns_my_suggestions/
